# Generated by Django 3.0 on 2021-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210823_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Hello, here you can see some of my favorite links', max_length=200),
        ),
    ]
