# Generated by Django 3.0 on 2021-09-26 09:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210923_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=0, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
