# Generated by Django 3.0 on 2021-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210926_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_login',
            field=models.BooleanField(default=False),
        ),
    ]
