# Generated by Django 3.0 on 2021-08-10 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leadfy.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Website', max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('short_url', models.SlugField(default=leadfy.utils.generate_ref_code, null=True)),
                ('link', models.URLField(default='http://www.google.com', null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(default='#9B23FA', max_length=100)),
                ('color2', models.CharField(default='#8AFBD8', max_length=100)),
                ('background_image_desktop', models.ImageField(default='defaultdesktopbackgroundimage.jpg', null=True, upload_to='usersbackgroundimages')),
                ('background_image_mobile', models.ImageField(default='defaultmobilebackgroundimage.jpg', null=True, upload_to='usersbackgroundimages')),
                ('background_image_brightness', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('use_background_image', models.BooleanField(default=False)),
                ('font_family', models.CharField(choices=[['aAlangkah.otf', 'aAlangkah.otf'], ['AmaticSC-Bold.ttf', 'AmaticSC-Bold.ttf'], ['arial.ttf', 'arial.ttf'], ['Juliagar.otf', 'Juliagar.otf']], default='arial.ttf', max_length=100, null=True)),
                ('primary_font_size', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('name_font_size', models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('border_radius', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('link_background_color', models.CharField(default='#000000', max_length=100)),
                ('link_text_color', models.CharField(default='#ffffff', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('referer', models.CharField(blank=True, max_length=200, null=True)),
                ('referer_main_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadfy.Link')),
            ],
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_submited', models.DateTimeField(default=django.utils.timezone.now)),
                ('referer', models.CharField(blank=True, max_length=200, null=True)),
                ('referer_main_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advanced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to_action', models.CharField(default='Before you go please, would you like to subscribe to my email list? Hint: You can skip this step if you wish.', max_length=150)),
                ('call_to_action_button_text', models.CharField(default='Subscribe', max_length=20)),
                ('seconds_to_wait_before_asking_user_to_subscribe_again', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(324000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
