# Generated by Django 3.0 on 2021-08-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadfy', '0002_auto_20210801_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAlangkah.otf', 'aAlangkah.otf'], ['aBusterDown.otf', 'aBusterDown.otf'], ['Alexross-Regular.ttf', 'Alexross-Regular.ttf'], ['AmaticSC-Bold.ttf', 'AmaticSC-Bold.ttf'], ['arial.ttf', 'arial.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Juliagar.otf', 'Juliagar.otf']], default='Heaters.otf', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Advanced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to_action', models.CharField(default='Would you like to subscribe to my email list?', max_length=100)),
                ('call_to_action_button_text', models.CharField(default='Subscribe', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
