# Generated by Django 3.0 on 2021-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0002_auto_20210702_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bio',
            field=models.CharField(blank=True, default='Tell your users about what you have to offer them here', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='button_text',
            field=models.CharField(default='Your cta', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.URLField(default='http://www.yourdestinationurl.com', null=True),
        ),
    ]
