# Generated by Django 3.0 on 2021-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0003_auto_20210702_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
