# Generated by Django 3.0 on 2021-08-12 15:49

from django.db import migrations, models
import leadfy.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0003_auto_20210812_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='ask_visitors_to_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.SlugField(default=leadfy.utils.generate_ref_code, null=True, unique=True),
        ),
    ]
