# Generated by Django 3.0 on 2021-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0003_auto_20210721_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='background_color_1',
            new_name='color1',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='background_color_2',
            new_name='color2',
        ),
        migrations.AddField(
            model_name='preferences',
            name='use_background_image',
            field=models.BooleanField(default=False),
        ),
    ]
