# Generated by Django 3.0 on 2021-08-04 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0003_auto_20210804_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='seconds_to_wait_before_asking_user_to_subscribe_again',
            field=models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(324000)]),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='call_to_action',
            field=models.CharField(default='Before you go please, would you like to subscribe to my email list? Hint: You can skip this step if you wish.', max_length=150),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='border_radius',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='#9B23FA', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='#8AFBD8', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAlangkah.otf', 'aAlangkah.otf'], ['AmaticSC-Bold.ttf', 'AmaticSC-Bold.ttf'], ['arial.ttf', 'arial.ttf'], ['Juliagar.otf', 'Juliagar.otf']], default='arial.ttf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_background_color',
            field=models.CharField(default='#000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_text_color',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='name_font_size',
            field=models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
