# Generated by Django 3.0 on 2021-07-23 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0004_auto_20210722_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='background_image_brightness',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='preferences',
            name='primary_font_size',
            field=models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='#E8CBC0', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='#636FA4', max_length=100),
        ),
    ]
