# Generated by Django 3.0 on 2021-07-03 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0004_auto_20210702_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
