# Generated by Django 3.0 on 2021-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0004_auto_20210812_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='show_link',
            field=models.BooleanField(default=False),
        ),
    ]
