# Generated by Django 3.0 on 2021-07-27 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0005_auto_20210723_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='name_font_size',
            field=models.IntegerField(default=48, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
