# Generated by Django 3.0 on 2021-07-03 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0005_leadmodel_date_submited'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('referer', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadfy.Page')),
            ],
        ),
    ]
