# Generated by Django 3.0 on 2021-08-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0006_auto_20210813_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='netloc',
        ),
    ]
