# Generated by Django 3.0 on 2021-08-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0007_remove_link_netloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='body_font_color',
            field=models.CharField(default='rgb(255, 255, 255)', max_length=100),
        ),
    ]
