# Generated by Django 3.0 on 2021-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0007_auto_20210728_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='link_background_color',
            field=models.CharField(default='#fff', max_length=100),
        ),
        migrations.AddField(
            model_name='preferences',
            name='link_text_color',
            field=models.CharField(default='#fff', max_length=100),
        ),
    ]
