# Generated by Django 3.0 on 2021-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0008_preferences_body_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
