# Generated by Django 3.0 on 2021-08-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0011_auto_20210819_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='show_link',
        ),
    ]
