# Generated by Django 3.0 on 2021-08-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0012_remove_social_show_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
