# Generated by Django 3.0 on 2021-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0015_auto_20210819_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='custom_css_file',
            field=models.FileField(blank=True, null=True, upload_to='customstylesheets'),
        ),
    ]
