# Generated by Django 3.0 on 2021-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0016_preferences_custom_css_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='show_subscribe_button_in_links_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='use_this_link_to_ask_visitors_to_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
