# Generated by Django 3.0 on 2021-08-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0017_auto_20210819_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanced',
            old_name='ask_visitors_to_subscribe',
            new_name='ask_visitors_to_subscribe_when_they_click_in_a_link',
        ),
    ]
