# Generated by Django 3.0 on 2021-08-21 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0018_auto_20210819_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='pinterest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='snapchat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='call_to_action',
            field=models.CharField(default='Would you like to subscribe to my email list? Hint: You can skip this step if you wish.', max_length=150),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='body_font_color',
            field=models.CharField(default='rgba(255, 255, 255, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='border_radius',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='rgba(220.04, 179.365, 255, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='rgba(161.738, 241.425, 240.989, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAlangkah.otf', 'aAlangkah.otf'], ['AmaticSC-Bold.ttf', 'AmaticSC-Bold.ttf'], ['arial.ttf', 'arial.ttf'], ['Juliagar.otf', 'Juliagar.otf']], default='Juliagar.otf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_background_color',
            field=models.CharField(default='rgba(0, 0, 0, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_text_color',
            field=models.CharField(default='rgba(255, 255, 255, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='spotify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
