# Generated by Django 3.0 on 2021-08-21 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadfy', '0020_lntegrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lntegrations',
            new_name='Integrations',
        ),
    ]
