# Generated by Django 3.0 on 2021-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0021_auto_20210821_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='link_border_color',
            field=models.CharField(default=models.CharField(default='rgba(0, 0, 0, 1)', max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['AmaticSC-Bold.ttf', 'AmaticSC-Bold.ttf'], ['arial.ttf', 'arial.ttf'], ['Juliagar.otf', 'Juliagar.otf']], default='Juliagar.otf', max_length=100, null=True),
        ),
    ]
