# Generated by Django 3.0 on 2021-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0022_auto_20210822_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='link_border_color',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
