# Generated by Django 3.0 on 2021-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0024_auto_20210823_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='location_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='location_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
