# Generated by Django 3.0 on 2021-08-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0025_auto_20210823_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='snapchat',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
