# Generated by Django 3.0 on 2021-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0026_auto_20210825_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='os_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
