# Generated by Django 3.0 on 2021-08-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadfy', '0027_auto_20210826_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='show_subscribe_button_in_links_page',
        ),
        migrations.AlterField(
            model_name='advanced',
            name='ask_visitors_to_subscribe_when_they_click_in_a_link',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubscribeButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_subscribe_button_in_links_page', models.BooleanField(default=False)),
                ('call_to_action', models.CharField(default='Would you like to subscribe to my email list? Hint: You can skip this step if you wish.', max_length=150)),
                ('call_to_action_button_text', models.CharField(default='Subscribe', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
