# Generated by Django 3.0 on 2021-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0028_auto_20210829_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribebutton',
            name='show_subscribe_button_in_links_page',
        ),
        migrations.AddField(
            model_name='subscribebutton',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='use_this_link_to_ask_visitors_to_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribebutton',
            name='call_to_action',
            field=models.CharField(default='Would you like to subscribe to my email list?', max_length=150),
        ),
    ]
