# Generated by Django 3.0 on 2021-08-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0029_auto_20210829_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced',
            name='ask_visitors_to_subscribe_when_they_click_in_a_link',
        ),
    ]
