# Generated by Django 3.0 on 2021-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0030_remove_advanced_ask_visitors_to_subscribe_when_they_click_in_a_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='custom_css_file',
        ),
        migrations.AddField(
            model_name='preferences',
            name='lastmodified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
