# Generated by Django 3.0 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0031_auto_20210901_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='lastmodified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
