# Generated by Django 3.0 on 2021-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0032_auto_20210901_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAffirmation.otf', 'aAffirmation.otf'], ['aAlangkah.otf', 'aAlangkah.otf'], ['aAlwaysSmile.otf', 'aAlwaysSmile.otf'], ['aAnekdot.otf', 'aAnekdot.otf'], ['aAtos.otf', 'aAtos.otf'], ['aBusterDown.otf', 'aBusterDown.otf'], ['AmaticSC-Regular.ttf', 'AmaticSC-Regular.ttf'], ['AmongUs-Regular.ttf', 'AmongUs-Regular.ttf'], ['arial.ttf', 'arial.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Forturn.otf', 'Forturn.otf'], ['Hiatus.otf', 'Hiatus.otf'], ['JeromeRomusha.ttf', 'JeromeRomusha.ttf'], ['Juliagar.otf', 'Juliagar.otf'], ['LT Feelgood Rough Bold.ttf', 'LT Feelgood Rough Bold.ttf'], ['LT Feelgood Rough.ttf', 'LT Feelgood Rough.ttf'], ['Masker Area.otf', 'Masker Area.otf'], ['Mirlor-Regular.ttf', 'Mirlor-Regular.ttf'], ['Multi-Regular.ttf', 'Multi-Regular.ttf'], ['No Virus.otf', 'No Virus.otf'], ['Pencil-Regular.ttf', 'Pencil-Regular.ttf']], default='Juliagar.otf', max_length=100, null=True),
        ),
    ]
