# Generated by Django 3.0 on 2021-09-15 09:29

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0033_auto_20210903_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='background_image_desktop',
            field=django_resized.forms.ResizedImageField(crop=None, default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1280, 720], upload_to='usersbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='background_image_mobile',
            field=django_resized.forms.ResizedImageField(crop=None, default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[720, 1280], upload_to='usersbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='border_radius',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='rgba(180.468, 151.605, 207.461, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='rgba(252.309, 234.818, 179.729, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_background_color',
            field=models.CharField(default='rgba(255, 255, 255, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_border_color',
            field=models.CharField(default='rgba(255, 255, 255, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='link_text_color',
            field=models.CharField(default='rgba(0, 0, 0, 1)', max_length=100),
        ),
    ]
