# Generated by Django 3.0 on 2021-09-23 18:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0035_auto_20210915_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='background_image_desktop',
            field=django_resized.forms.ResizedImageField(crop=None, default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', force_format='JPEG', keep_meta=True, null=True, quality=30, size=[1920, 1080], upload_to='usersbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='background_image_mobile',
            field=django_resized.forms.ResizedImageField(crop=None, default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', force_format='JPEG', keep_meta=True, null=True, quality=30, size=[1080, 1920], upload_to='usersbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAffirmation.otf', 'aAffirmation.otf'], ['aAlwaysSmile.otf', 'aAlwaysSmile.otf'], ['AmaticSC-Regular.ttf', 'AmaticSC-Regular.ttf'], ['arial.ttf', 'arial.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Juliagar.otf', 'Juliagar.otf'], ['No Virus.otf', 'No Virus.otf']], default='Juliagar.otf', max_length=100, null=True),
        ),
    ]
