# Generated by Django 3.0 on 2021-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0038_remove_social_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='background_image_desktop',
            field=models.ImageField(default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', null=True, upload_to='usersbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='background_image_mobile',
            field=models.ImageField(default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', null=True, upload_to='usersbackgroundimages'),
        ),
    ]
