# Generated by Django 3.0 on 2021-10-08 13:56

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0041_social_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='preferences',
            name='border_radius',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='rgba(130.517, 189.457, 212.85, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='rgba(151.462, 111.687, 143.872, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='font_family',
            field=models.CharField(choices=[['aAffirmation.otf', 'aAffirmation.otf'], ['aAlwaysSmile.otf', 'aAlwaysSmile.otf'], ['AmaticSC-Regular.ttf', 'AmaticSC-Regular.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Juliagar.otf', 'Juliagar.otf'], ['Karla-VariableFont_wght.ttf', 'Karla-VariableFont_wght.ttf'], ['No Virus.otf', 'No Virus.otf']], default='Karla-VariableFont_wght.ttf', max_length=100, null=True),
        ),
    ]
