# Generated by Django 3.0 on 2021-10-08 14:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0042_auto_20211008_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
