# Generated by Django 3.0 on 2021-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0043_auto_20211008_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscribebutton',
            name='call_to_action_button_text',
            field=models.CharField(default='Subscribe', max_length=50),
        ),
    ]
