# Generated by Django 3.0 on 2021-10-11 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0044_auto_20211009_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='template_thumbnails')),
                ('color1', models.CharField(default='rgba(130.517, 189.457, 212.85, 1)', max_length=100)),
                ('color2', models.CharField(default='rgba(151.462, 111.687, 143.872, 1)', max_length=100)),
                ('body_font_color', models.CharField(default='rgba(255, 255, 255, 1)', max_length=100)),
                ('background_image_desktop', models.ImageField(default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', null=True, upload_to='usersbackgroundimages')),
                ('background_image_mobile', models.ImageField(default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', null=True, upload_to='usersbackgroundimages')),
                ('background_image_brightness', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('use_background_image', models.BooleanField(default=False)),
                ('font_family', models.CharField(choices=[['aAffirmation.otf', 'aAffirmation.otf'], ['aAlwaysSmile.otf', 'aAlwaysSmile.otf'], ['AmaticSC-Regular.ttf', 'AmaticSC-Regular.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Juliagar.otf', 'Juliagar.otf'], ['Karla-VariableFont_wght.ttf', 'Karla-VariableFont_wght.ttf'], ['No Virus.otf', 'No Virus.otf']], default='Karla-VariableFont_wght.ttf', max_length=100, null=True)),
                ('primary_font_size', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('name_font_size', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('border_radius', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('link_background_color', models.CharField(default='rgba(255, 255, 255, 1)', max_length=100)),
                ('link_border_color', models.CharField(default='rgba(255, 255, 255, 1)', max_length=100)),
                ('link_text_color', models.CharField(default='rgba(0, 0, 0, 1)', max_length=100)),
                ('lastmodified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
