# Generated by Django 3.0 on 2021-10-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0045_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='template',
            field=models.CharField(default='custom', max_length=50),
        ),
    ]
