# Generated by Django 3.0 on 2021-11-13 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadfy', '0046_preferences_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='show_watermark',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribebutton',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribebutton',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image_brightness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image_desktop',
            field=models.ImageField(default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', null=True, upload_to='templatesbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image_mobile',
            field=models.ImageField(default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', null=True, upload_to='templatesbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='font_family',
            field=models.CharField(choices=[['aAffirmation.otf', 'aAffirmation.otf'], ['aAlwaysSmile.otf', 'aAlwaysSmile.otf'], ['AmaticSC-Regular.ttf', 'AmaticSC-Regular.ttf'], ['CirrusWisp.otf', 'CirrusWisp.otf'], ['Juliagar.otf', 'Juliagar.otf'], ['Karla-VariableFont_wght.ttf', 'Karla-VariableFont_wght.ttf'], ['No Virus.otf', 'No Virus.otf']], default='Juliagar.otf', max_length=100, null=True),
        ),
    ]
