# Generated by Django 3.0 on 2021-11-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadfy', '0047_auto_20211113_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='color1',
            field=models.CharField(default='rgba(0, 0, 0, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='color2',
            field=models.CharField(default='rgba(90, 90, 90, 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image_desktop',
            field=models.ImageField(blank=True, default='usersbackgroundimages/defaultdesktopbackgroundimage.jpg', null=True, upload_to='templatesbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='background_image_mobile',
            field=models.ImageField(blank=True, default='usersbackgroundimages/defaultmobilebackgroundimage.jpg', null=True, upload_to='templatesbackgroundimages'),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='template_thumbnails'),
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_1', models.URLField(blank=True, null=True)),
                ('embed_2', models.URLField(blank=True, null=True)),
                ('embed_3', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
