# Generated by Django 3.0 on 2021-11-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0048_auto_20211115_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embed',
            old_name='embed_1',
            new_name='youtube_video_id',
        ),
        migrations.RemoveField(
            model_name='embed',
            name='embed_2',
        ),
        migrations.RemoveField(
            model_name='embed',
            name='embed_3',
        ),
    ]
