# Generated by Django 3.0 on 2021-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0055_auto_20211117_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcss',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='customstylesheets'),
        ),
    ]
