# Generated by Django 3.0 on 2021-11-21 17:58

from django.db import migrations, models
import leadfy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('leadfy', '0056_auto_20211121_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcss',
            name='css_file',
            field=models.FileField(blank=True, null=True, storage=leadfy.storage.OverwriteStorage(), upload_to='customstylesheets'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
