# Generated by Django 3.0 on 2021-08-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paid_until',
        ),
    ]
